### ISSUE TITLE
pair programing class 5, 301

### ISSUE THREAD

**Issue by shaynereedsmith** [austriker27/personal-portfolio#6]
1. in `projectView.js` we see this:

> //this code makes you scroll to the top of section
$('#aboutMe').on('click', function(){
  $('main').hide();
  $('main [class="'+$(this).attr('data-content')+'"]').fadeIn();
  $('html, body').animate({
    scrollTop: $('#bannerText').position().top
  });
});

The `scrollTop` method gets the current vertical position of the scroll bar for the first element in the set of matched elements or set the vertical position of the scroll bar for every matched element. For instance, if you had scrolled 50 px from the top of the div, the return for scrollTop() would be "50". I believe the method you're looking for if you want the screen to scroll to the top when the `#aboutMe` id is clicked would be `scrollTo(0, 0)`

2. Projects objects should be hidden initially (according to latest specs). This can be done by setting a css class that hides the element to the parent, ex: `.hide {display: none}`, and then toggling that or changing its css on click using jQuery.

3. Hamburger menu button is set to activate on hover using css. This is problematic because the navigation will disappear once the mouse leaves the hamburger button, which it must do in order to use the navigation. This is not exactly an issue in mobile view because hover acts more like an on-click function in mobile. However it would probably be best if this were a jQuery event handler function.

**Comment by austriker27** [comment]
Fixed issue #1!

**Comment by austriker27** [comment]
fixed all issues!
